version: '3'

services:
    web:
        build: ./web
        ports: 
            - 80:80
        volumes:
            - $APP_PATH:$APP_CONTAINER_PATH
        container_name: webserver
        depends_on:
            - db

    db:
        image: mysql
        container_name: database
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306
        volumes:
            - $DB_PATH:/var/lib/mysql



