version: '3'

services:
    web:
        build: ./web
        ports: 
            - 80:80
        volumes: 
            - $APP_PATH:$APP_CONTAINER_PATH
        environment: 
            APACHE_RUN_USER: '#1000'
        depends_on: [db]
        container_name: webserver

    db:
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
        restart: always
        volumes: 
            - $DB_PATH:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
        container_name: database
