version: '3'

services:
    php:
        build: ./web
        depends_on: ['db']
        volumes:
            - $APP_PATH:$APP_CONTAINER_PATH
            - ./web/php.ini:/usr/local/etc/php/php.ini
        container_name: php

    nginx:
        image: nginx
        ports:
            - 80:80
            - 4430:443
        volumes:
            - $APP_PATH:$APP_CONTAINER_PATH
            - ./web/vhosts/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on: ['php']
        container_name: nginx

    db:
        image: mysql
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
        volumes: 
            - $DB_PATH:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
        restart: always
        container_name: databases
